### ISSUE TITLE
Common Tensor operators/constructors in PyTorch

### ISSUE THREAD

**Issue by KDr2** [TuringLang/ThArrays.jl#1]
Relevant links:

- C++ functions in namespaces `at`: https://pytorch.org/cppdocs/api/namespace_at.html#functions
- Python API of class `Tensor`: https://pytorch.org/docs/stable/tensors.html

**Comment by KDr2** [comment]
Since we have auto-generated a bunch of methods from the c++ source, and have another issue(#4) opened, could we close this one? @yebai

**Comment by yebai** [comment]
Sounds good, but maybe worth to save the python API list somewhere (e.g. docs/python_api). Also, it is worth to create a similar list for low-level Julia API which directly calls the C functions. This allows working with low-level API when a suitable Julia method is not defined yet.

**Comment by KDr2** [comment]
Documented at https://github.com/TuringLang/ThArrays.jl/blob/master/docs/index.md.
