### ISSUE TITLE
Maybe move all Julia wrapper functions into a submodule

### ISSUE THREAD

**Issue by yebai** [TuringLang/ThArrays.jl#10]
Maybe move all low-level Julia functions that calls C functions into a submodule, e.g. `ThArrays.ThC`, so that their methods can be distinguished from other Julia functions. 

Besides, perhaps check into the repo the file generated by [`api_generator.jl`](https://github.com/TuringLang/ThArrays.jl/blob/master/src/api_generator.jl), since it is helpful to look at the file to find certain functions.

**Comment by KDr2** [comment]
Done.

**Comment by yebai** [comment]
Thanks, perhaps move all `ThC` files into a subfolder `src/thc`? Also, any reason for exporting all the `ThC.*` methods? We can probably access these methods using the prefix like `ThC.sin` everywhere.

**Comment by KDr2** [comment]
Module `ThC` is only a single file, so I think it's OK to just simply leave it in the src folder.

I export the methods in `ThC` for convenience over explicitness, you are right, explicitness is more important. I will remove the exporting statement. But for your example, some functions have a homonymous method in the `Base` module, like, `abs`, `sin`, ..., for these functions, I extended their homonymous methods in the `Base` module, so we don't need the `ThC` qualifier when using them, is this OK in your opinion?

**Comment by yebai** [comment]
> I extended their homonymous methods in the Base module, so we don't need the ThC qualifier when using them, is this OK in your opinion?

Sounds good!

> And for other functions that have no homonymous method, should we delete the export statement for it?

Yes, let's delete them and introduce (high-level) Julia functions.

**Comment by yebai** [comment]
> Module ThC is only a single file, so I think it's OK to just simply leave it in the src folder.

How about moving both `thc.jl` and `thc-generator.jl` into `src/thc`? This makes things more explicit thus a bit more readable I think.

**Comment by KDr2** [comment]
All done.
