### ISSUE TITLE
Avoid memory copying when creating Tensor from Julia Array?

### ISSUE THREAD

**Issue by yebai** [TuringLang/ThArrays.jl#12]
I wonder whether it is possible to share data between Julia Array and PyTorch Tensor? I understand that memory-wise, PyTorch is row-major while Julia uses column-major. But is there a switch that would allow PyTorch to use column-major, or Julia row-major?

The following API might be related:

- https://pytorch.org/docs/stable/tensor_attributes.html#torch-layout
- https://pytorch.org/cppdocs/api/function_namespacetorch_1ad7fb2a7759ef8c9443b489ddde494787.html#function-documentation

**Comment by KDr2** [comment]
It's totally viable, will give a try tomorrow.

**Comment by KDr2** [comment]
Done by https://github.com/TuringLang/ThArrays.jl/commit/843ec9382b19091d51c84178ab1b35dcce4c9e5e.

**Comment by yebai** [comment]
thanks!
