### ISSUE TITLE
Add basic support for TorchScipt

### ISSUE THREAD

**Issue by yebai** [TuringLang/ThArrays.jl#15]
It would be helpful to explore some basic TorchScipt API, by

- passing TorchScipt in the form of strings, and 
- return a callable object that can be wrapped into a Julia function. 

In the longer term, we can gradually experiment with tracing Julia programs into some IR format which can be JIT'ed by PyTorch's C++ JIT API.

**Comment by KDr2** [comment]
Done by https://github.com/TuringLang/ThArrays.jl/commit/257c230c3e1d4980d3be7fa00763873fefd1225b.
