### ISSUE TITLE
Mimic TrackedArray API from Tracker

### ISSUE THREAD

**Issue by yebai** [TuringLang/ThArrays.jl#4]
I wonder whether it is sensible to mimic the `TrackedArray` type and API from [Tracker](https://github.com/FluxML/Tracker.jl) first. This has a similar purpose with #1, but takes a top-down approach by only wrapping stuff in PyTorch C++ library that we need for implementing `TrackedArray`. In addition,  similar wrapping can be done for `TrackedReal`.

@KDr2 can you take a look at both #1 and [`TrackedArray`](https://github.com/FluxML/Tracker.jl/blob/master/src/lib/array.jl) and see which approach might be more sensible?

**Comment by KDr2** [comment]
Since #14 is merged, could we close this issue?
